name: Build and Release Artifact

on:
  push:
    tags:
      - 'v*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List repository contents
        run: ls -la

      - name: List devicePEQ directory contents
        run: ls -la devicePEQ

      - name: Archive just the plugin Folder
        run: |
          zip -r devicePEQ.zip devicePEQ

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: devicePEQ.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
